$('.drag').draggable({ 
  appendTo: 'body',
  helper: 'clone'
});

$('#dropzone').droppable({
//  activeClass: 'active',
  hoverClass: 'hover',
  accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
  drop: function (e, ui) {
    var $el = $('<div class="drop-item"><details><summary>' + ui.draggable.text() + '</summary><div><label>More Data</label><input type="text" /></div></details></div>');
    $el.append($('<button type="button" class="btn btn-default btn-xs remove"><span class="glyphicon glyphicon-trash"></span></button>').click(function () { $(this).parent().detach(); }));
    $(this).append($el);
  }
}).sortable({
  items: '.drop-item',
  sort: function() {
    // gets added unintentionally by droppable interacting with sortable
    // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
    $( this ).removeClass( "active" );
  }
});

$('#tuozhuai').droppable({
//	  activeClass: 'active',
	  hoverClass: 'hover',
	  accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
	  drop: function (e, ui) {
	  }
	}).sortable({
	  items: '.panel',
	  sort: function() {
	    // gets added unintentionally by droppable interacting with sortable
	    // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
	    $( this ).removeClass( "active" );
	  }
	});
$('.pb_right').droppable({
//	activeClass: 'active',
	hoverClass: 'hover',
	accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
	drop: function (e, ui) {
	}
}).sortable({
	items: '.btn',
	sort: function() {
		// gets added unintentionally by droppable interacting with sortable
		// using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
		$( this ).removeClass( "active" );
	}
});


var parentMenuNum = 0;
function addParentMenu() {
	parentMenuNum+=1;
	var html = '<div class="panel panel-default">';
	html += '<div class="panel-heading" role="tab" id="heading_'+parentMenuNum+'">';
	html += '<div class="panel-title clearfix">';
	html += '<div class="parent_left" data-toggle="collapse"';
	html += 'data-parent="#accordion" href="#collapse_'+parentMenuNum+'"';
	html += 'aria-expanded="false" aria-controls="collapse_'+parentMenuNum+'">';
	html += '<span class="glyphicon glyphicon-list"></span> <span>菜单名称'+parentMenuNum+'</span>';
	html += '</div>';
	html += '<div class="parent_right">';
	html += '<span class="glyphicon glyphicon-plus"></span>';
	html += '<span class="glyphicon glyphicon-trash"></span>';
	html += '</div>';
	html += '</div>';
	html += '</div>';
	html += '<div id="collapse_'+parentMenuNum+'" class="panel-collapse collapse"';
	html += 'role="tabpanel" aria-labelledby="heading_'+parentMenuNum+'">';
	html += '<div class="panel-body">';
	html += '<div class="pb_left">图片</div>';
	html += '<div class="pb_right">';
	html += '<span class="btn btn-default">111111111111</span> <span';
	html += 'class="btn btn-default">222222222222</span> <span';
	html += 'class="btn btn-default">333333333333</span>';
	html += '</div>';
	html += '</div>';
	html += '</div>';
	html += '</div>';
	$("#accordion").append(html);
}